name: QA On-Demand Environment

on:
  push:
    branches:
      - 'feature/**'
      - 'main'
  pull_request:
    types: [closed]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    env:
      PROJECT: qa-aci
      BRANCH_NAME: ${{ github.ref_name }}
      PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Pulumi CLI
        uses: pulumi/actions@v4

      - name: Install dependencies
        run: pip install pulumi pulumi-azure-native

      - name: Pulumi login
        run: pulumi login --local

      - name: Sanitize branch name
        run: echo "SANITIZED_BRANCH_NAME=${BRANCH_NAME//\//-}" >> $GITHUB_ENV

      - name: Detect Pulumi org
        id: pulumi_org
        run: echo "ORG=$(pulumi whoami --show-org)" >> $GITHUB_ENV

      - name: Pulumi stack select/create
        working-directory: infrastructure
        run: |
          STACK="$ORG/$PROJECT/$SANITIZED_BRANCH_NAME"
          pulumi stack select "$STACK" || pulumi stack init "$STACK"
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      - name: Apply Pulumi.dev.yaml config to stack
        working-directory: infrastructure
        run: cp Pulumi.dev.yaml Pulumi."$SANITIZED_BRANCH_NAME".yaml
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}

      - name: Pulumi preview
        working-directory: infrastructure
        run: pulumi preview
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
